
package io.spring.guides.gs_producing_web_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import countries.core.common.AddCountryRequest;
import countries.core.common.AddCountryResponse;
import countries.core.common.DeleteCountryRequest;
import countries.core.common.DeleteCountryResponse;
import countries.core.common.GetCountryRequest;
import countries.core.common.GetCountryResponse;
import countries.core.common.LoginUserRequest;
import countries.core.common.LoginUserResponse;
import countries.core.common.LogoutUserRequest;
import countries.core.common.LogoutUserResponse;
import countries.core.common.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CountriesPort", targetNamespace = "http://spring.io/guides/gs-producing-web-service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CountriesPort {


    /**
     * 
     * @param addCountryRequest
     * @return
     *     returns countries.core.AddCountryResponse
     */
    @WebMethod
    @WebResult(name = "addCountryResponse", targetNamespace = "core.countries", partName = "addCountryResponse")
    public AddCountryResponse addCountry(
        @WebParam(name = "addCountryRequest", targetNamespace = "core.countries", partName = "addCountryRequest")
        AddCountryRequest addCountryRequest);

    /**
     * 
     * @param getCountryRequest
     * @return
     *     returns countries.core.GetCountryResponse
     */
    @WebMethod
    @WebResult(name = "getCountryResponse", targetNamespace = "core.countries", partName = "getCountryResponse")
    public GetCountryResponse getCountry(
        @WebParam(name = "getCountryRequest", targetNamespace = "core.countries", partName = "getCountryRequest")
        GetCountryRequest getCountryRequest);

    /**
     * 
     * @param loginUserRequest
     * @return
     *     returns countries.core.LoginUserResponse
     */
    @WebMethod
    @WebResult(name = "loginUserResponse", targetNamespace = "core.countries", partName = "loginUserResponse")
    public LoginUserResponse loginUser(
        @WebParam(name = "loginUserRequest", targetNamespace = "core.countries", partName = "loginUserRequest")
        LoginUserRequest loginUserRequest);

    /**
     * 
     * @param logoutUserRequest
     * @return
     *     returns countries.core.LogoutUserResponse
     */
    @WebMethod
    @WebResult(name = "logoutUserResponse", targetNamespace = "core.countries", partName = "logoutUserResponse")
    public LogoutUserResponse logoutUser(
        @WebParam(name = "logoutUserRequest", targetNamespace = "core.countries", partName = "logoutUserRequest")
        LogoutUserRequest logoutUserRequest);

    /**
     * 
     * @param deleteCountryRequest
     * @return
     *     returns countries.core.DeleteCountryResponse
     */
    @WebMethod
    @WebResult(name = "deleteCountryResponse", targetNamespace = "core.countries", partName = "deleteCountryResponse")
    public DeleteCountryResponse deleteCountry(
        @WebParam(name = "deleteCountryRequest", targetNamespace = "core.countries", partName = "deleteCountryRequest")
        DeleteCountryRequest deleteCountryRequest);

}
